apps:
  - app_name: tty-clock
    repo: https://github.com/xorg62/tty-clock
    targets:
      - make
      - make install
    dependencies:
      - ncurses-devel

  - app_name: xcape
    repo: https://github.com/alols/xcape
    targets:
      - make all
      - make install
      - make clean
    dependencies:
      - git 
      - gcc 
      - make 
      - pkgconfig 
      - libX11-devel 
      - libXtst-devel 
      - libXi-devel

  - app_name: i3lock-color
    repo: https://github.com/Raymo111/i3lock-color
    targets:
      - "./build.sh"
      - "cd build && make install"
    dependencies:
      - autoconf
      - automake
      - libev-devel
      - xcb-util-image-devel
      - xcb-util-xrm-devel
      - libxkbcommon-devel
      - libxkbcommon-x11-devel
      - cairo-devel
      - libjpeg-turbo-devel
      - pam-devel

  - app_name: betterlockscreen
    repo: https://github.com/pavanjadhaw/betterlockscreen
    targets:
      - "cp betterlockscreen /usr/bin/"
    dependencies:
      - ncurses-devel

  - app_name: tdrop
    repo: https://github.com/noctuid/tdrop
    targets:
      - make install
    dependencies:
      - xdotool

  - app_name: xdo
    repo: https://github.com/baskerville/xdo
    targets:
      - make
      - make install
    dependencies:
      - xcb-util-wm-devel

  - app_name: xtitle
    repo: https://github.com/baskerville/xtitle
    targets:
      - make
      - make install
    dependencies:
      - gcc

  - app_name: interception-tools
    repo: https://gitlab.com/interception/linux/tools.git
    targets:
      - cmake -B build -DCMAKE_BUILD_TYPE=Release
      - cmake --build build
      - "cp -f build/udevmon /usr/bin"
      - "cp -f build/intercept /usr/bin"
      - "cp -f build/uinput /usr/bin"
      - "cp -f udevmon.service /etc/systemd/system/"
    dependencies:
      - g++
      - cmake
      - libevdev-devel 
      - systemd-devel
      - yaml-cpp-devel
      - boost-devel

  - app_name: dual-function-keys-plugin
    repo: https://gitlab.com/interception/linux/plugins/dual-function-keys
    targets:
      - make
      - make install
    dependencies:
      - cmake
      - libevdev-devel 
      - systemd-devel
      - yaml-cpp-devel
      - boost-devel

  - app_name: space2meta
    repo: https://gitlab.com/interception/linux/plugins/space2meta
    targets:
      - cmake -Bbuild
      - cmake --build build 
      - "cp -f build/space2meta /usr/local/bin"
    dependencies:
      - cmake
      - libevdev-devel 
      - systemd-devel
      - yaml-cpp-devel
      - boost-devel

  - app_name: pulseaudio-ctl
    repo: https://github.com/graysky2/pulseaudio-ctl
    targets:
      - make
      - make install
    dependencies:
      - bc

  - app_name: bsp-layout
    repo: https://github.com/phenax/bsp-layout
    targets:
      - make
      - make install
    dependencies:
      - gcc

  - app_name: unclutter
    repo: https://github.com/Airblader/unclutter-xfixes
    targets:
      - make
      - make install
    dependencies:
      - gcc
      - asciidoc
