
[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Underline"

[general]
import = ["/home/jpaulo/.config/alacritty/themes/themes/seoul256-light.toml"]
