# Pacotes Virtualizacao
kvm_packages:
  - qemu
  - virt-manager
  - virt-viewer
  - dnsmasq
  - vde2
  - libvirt
  - bridge-utils
  - openbsd-netcat
  - dmidecode
  - ovmf
  - iptables-nft
  - ebtables
