# Network vars caso queira configurar bridge com endereco manual
# conn_name:
# bridge_name:
# ip_address:
# gateway:
# dns1:
# dns2:

# Pacotes Virtualizacao
kvm_packages:
  - qemu-kvm
  - libvirt
  - virt-install
  - virt-manager
