    # Fedora 32 usa versao do CGroup e NFtables incompativeis com Docker.
    # Necessario setar a versao mais antiga via grub
    - name: Habilita versao antiga CGroups
      command: 'grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"'
      changed_when: false
      tags: docker

    - name: Adiciona interface docker zona trusted
      firewalld:
        zone: trusted
        interface: docker0
        state: enabled
        permanent: true
      tags: firewall

    - name: Adiciona add-masquerade
      firewalld:
        zone: FedoraWorkstation
        masquerade: "yes"
        state: enabled
        permanent: true
      tags: firewall

    - name: Instala pacotes necessarios para Docker
      dnf:
        name:
          "{{ docker_packages }}"
        state: present
      notify: Habilita docker

    - name: Adiciona usuario ao grupo docker
      user:
        name: "{{ lookup('env','LOGNAME') }}"
        groups: docker
        append: yes
      tags: debug
