    - name: Cria diretorio necessario
      file:
        path: "$HOME/.local/share/nvim/site/pack/packer/start"
        state: directory
      tags: nvim

    - name: Instala gerenciador de plugin packer.nvim
      git:
        repo: https://github.com/wbthomason/packer.nvim.git
        dest: "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
      tags: nvim

    - name: Instala plugins nvim
      shell:
        cmd: nvim -es -u ~/.config/nvim/lua/plugins.lua -c "packadd packer.nvim | lua require('plugins').install() " -c "sleep 50"
      tags: nvim
      # register: instala_plugin_output
      # changed_when: instala_plugin_output.stdout.find('Cloning into') != -1
