      # https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
    - name: Instala plugins nvim lazy plugin manager
      shell:
        # cmd: nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync' --headless
        cmd: nvim --headless "+Lazy! sync" +qa
      tags: nvim
