    - name: Cria diretorio necessario
      file:
        path: "$HOME/.local/share/nvim/site/pack/packer/start"
        state: directory
      tags: nvim

    - name: Instala gerenciador de plugin packer.nvim
      git:
        repo: https://github.com/wbthomason/packer.nvim.git
        dest: "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"
      tags: nvim

      # tip from 
      # https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
    - name: Instala plugins nvim
      shell:
        cmd: nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync' --headless
      tags: nvim
      # register: instala_plugin_output
      # changed_when: instala_plugin_output.stdout.find('Cloning into') != -1
